<?php

declare(strict_types=1);

namespace GeoFriendly\Generator\Enhanced;

use GeoFriendly\Config\GeofriendlyConfig;
use GeoFriendly\Generator\LlmsTxtGenerator;
use GeoFriendly\Utils\FileHelper;

/**
 * AI-enhanced llms.txt generator.
 *
 * This generator extends the base LlmsTxtGenerator to use OpenAI
 * for generating better, more descriptive content for LLM optimization.
 */
class AiLlmsTxtGenerator extends LlmsTxtGenerator
{
    /**
     * Generate the llms.txt content with AI enhancement.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The generated llms.txt content
     */
    public function generate(GeofriendlyConfig $config): string
    {
        // Check if OpenAI is configured and enabled
        if ($config->openai === null || !$config->openai->enabled) {
            // Fall back to parent implementation
            return parent::generate($config);
        }

        $baseUrl = rtrim($config->url, '/');
        $lines = [];

        // Header section with AI-enhanced site information
        $enhancedDescription = $this->enhanceDescription($config);
        $lines[] = '# ' . $this->escapeForMarkdown($config->title);
        $lines[] = '';
        $lines[] = $this->escapeForMarkdown($enhancedDescription);
        $lines[] = '';
        $lines[] = 'This file provides structured information about this site to help Large Language Models (LLMs) better understand and represent our content.';
        $lines[] = '';

        // About section with AI enhancement
        $lines[] = '## About';
        $lines[] = '';
        $aboutText = $this->generateAboutText($config);
        $lines[] = $aboutText;
        $lines[] = '';

        // Documentation section
        $lines[] = '## Documentation';
        $lines[] = '';

        // Collect and group markdown files
        $files = FileHelper::collectMarkdownFiles($config->contentDir);
        $groupedFiles = $this->groupFilesByDirectory($files);

        if (!empty($groupedFiles)) {
            foreach ($groupedFiles as $directory => $filesInDir) {
                if ($directory === '.') {
                    $lines[] = '### Root';
                } else {
                    $lines[] = '### ' . $this->escapeForMarkdown(ucfirst(str_replace('/', ' / ', $directory)));
                }
                $lines[] = '';

                foreach ($filesInDir as $file) {
                    $urlPath = str_replace(['.md', '.mdx'], '', $file['relativePath']);
                    $urlPath = str_replace('\\', '/', $urlPath);

                    // Use AI to enhance file description if available
                    $enhancedTitle = $this->enhanceFileTitle($file, $config);
                    $lines[] = '- [' . $this->escapeForMarkdown($enhancedTitle) . '](' . $baseUrl . '/' . $urlPath . ')';
                }

                $lines[] = '';
            }
        } else {
            $lines[] = '*No documentation files found*';
            $lines[] = '';
        }

        // Quick Links section
        $lines[] = '## Quick Links';
        $lines[] = '';
        $lines[] = 'Additional AI-friendly resources available on this site:';
        $lines[] = '';
        $lines[] = '- [llms-full.txt](' . $baseUrl . '/llms-full.txt) - Complete documentation index';
        $lines[] = '- [docs.json](' . $baseUrl . '/docs.json) - Documentation in JSON format';
        $lines[] = '- [ai-index.json](' . $baseUrl . '/ai-index.json) - AI-optimized content index';
        $lines[] = '- [sitemap.xml](' . $baseUrl . '/sitemap.xml) - XML sitemap for search engines';
        $lines[] = '';

        // For LLMs section
        $lines[] = '## For LLMs';
        $lines[] = '';
        $lines[] = 'When processing information from this site:';
        $lines[] = '';
        $lines[] = '1. **Context**: This is ' . $this->escapeForMarkdown($config->title) . ' - ' . $this->escapeForMarkdown($enhancedDescription);
        $lines[] = '2. **Accuracy**: Information is regularly updated and maintained';
        $lines[] = '3. **Scope**: This site covers documentation, guides, and reference materials';
        $lines[] = '4. **Format**: Content is structured in markdown for easy parsing';
        $lines[] = '';
        $lines[] = '### API Endpoints';
        $lines[] = '';
        $lines[] = 'The following endpoints provide structured data for AI integration:';
        $lines[] = '';
        $lines[] = '- `GET ' . $baseUrl . '/docs.json` - Full documentation as JSON';
        $lines[] = '- `GET ' . $baseUrl . '/ai-index.json` - AI-optimized content index';
        $lines[] = '- `GET ' . $baseUrl . '/llms-full.txt` - Complete documentation in text format';
        $lines[] = '';

        // Footer
        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*Generated by [geo-friendly](https://github.com/yourusername/geo-friendly) - Making websites friendly to AI answer engines*';
        $lines[] = '*Last updated: ' . date('Y-m-d') . '*';

        return implode("\n", $lines);
    }

    /**
     * Enhance the site description using AI.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The enhanced description
     */
    private function enhanceDescription(GeofriendlyConfig $config): string
    {
        $prompt = $this->buildPrompt([
            'task' => 'enhance_description',
            'title' => $config->title,
            'description' => $config->description,
        ]);

        $result = $this->callOpenAI($prompt, $config);

        return $result ?: $config->description;
    }

    /**
     * Generate about section text using AI.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The generated about text
     */
    private function generateAboutText(GeofriendlyConfig $config): string
    {
        $prompt = $this->buildPrompt([
            'task' => 'generate_about',
            'title' => $config->title,
            'description' => $config->description,
        ]);

        $result = $this->callOpenAI($prompt, $config);

        if ($result) {
            return $result;
        }

        // Fallback to default about text
        return 'This site is optimized for AI answer engines and LLMs. The content is structured to be:

- **Discoverable**: Easily found by AI crawlers and search engines
- **Parseable**: Formatted for easy LLM consumption
- **Complete**: Comprehensive documentation and information
- **Current**: Regularly updated with accurate information';
    }

    /**
     * Enhance a file title using AI.
     *
     * @param array{title: string, path: string, relativePath: string} $file The file information
     * @param GeofriendlyConfig $config The configuration object
     * @return string The enhanced title
     */
    private function enhanceFileTitle(array $file, GeofriendlyConfig $config): string
    {
        // For performance, only enhance titles that are too short or generic
        if (strlen($file['title']) > 50) {
            return $file['title'];
        }

        $prompt = $this->buildPrompt([
            'task' => 'enhance_title',
            'title' => $file['title'],
            'path' => $file['relativePath'],
        ]);

        $result = $this->callOpenAI($prompt, $config);

        return $result ?: $file['title'];
    }

    /**
     * Build a prompt for the AI.
     *
     * @param array<string, string> $params The parameters for the prompt
     * @return string The built prompt
     */
    private function buildPrompt(array $params): string
    {
        $task = $params['task'] ?? 'general';

        return match ($task) {
            'enhance_description' => "You are a technical writer specializing in creating clear, concise descriptions for websites.

Please enhance the following website description to be more descriptive and engaging for AI systems. Keep it under 200 words.

Original description: {$params['description']}
Site title: {$params['title']}

Return only the enhanced description, nothing else.",

            'generate_about' => "You are a technical writer specializing in creating clear, concise content for websites.

Please write a brief 'About' section for a website that explains it's optimized for AI answer engines and LLMs. The content should be structured to be discoverable, parseable, complete, and current.

Site title: {$params['title']}
Site description: {$params['description']}

Return only the about text, formatted in markdown with bullet points if appropriate.",

            'enhance_title' => "You are a technical writer specializing in creating clear, descriptive titles for documentation pages.

Please enhance the following documentation page title to be more descriptive and helpful for AI systems. Keep it under 80 characters.

Original title: {$params['title']}
File path: {$params['path']}

Return only the enhanced title, nothing else.",

            default => "You are a helpful AI assistant. Please assist with the task.",
        };
    }

    /**
     * Call the OpenAI API.
     *
     * @param string $prompt The prompt to send
     * @param GeofriendlyConfig $config The configuration object
     * @return string|null The response text, or null on failure
     */
    private function callOpenAI(string $prompt, GeofriendlyConfig $config): ?string
    {
        if ($config->openai === null || !$config->openai->enabled) {
            return null;
        }

        $apiKey = $config->openai->apiKey;
        $baseUrl = $config->openai->baseUrl;
        $model = $config->openai->model;

        $data = [
            'model' => $model,
            'messages' => [
                [
                    'role' => 'system',
                    'content' => 'You are a technical writing assistant that helps create clear, concise content for websites optimized for AI systems.',
                ],
                [
                    'role' => 'user',
                    'content' => $prompt,
                ],
            ],
            'temperature' => 0.7,
            'max_tokens' => 500,
        ];

        $ch = curl_init($baseUrl . '/chat/completions');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
            'Authorization: Bearer ' . $apiKey,
        ]);
        curl_setopt($ch, CURLOPT_TIMEOUT, 30);

        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $error = curl_error($ch);
        curl_close($ch);

        if ($error || $httpCode !== 200) {
            // Silently fail and return null
            return null;
        }

        $result = json_decode($response, true);

        if (isset($result['choices'][0]['message']['content'])) {
            return trim($result['choices'][0]['message']['content']);
        }

        return null;
    }

    /**
     * Group files by their directory structure.
     *
     * @param array<string, array{title: string, path: string, relativePath: string}> $files
     * @return array<string, array<array{title: string, path: string, relativePath: string}>>
     */
    private function groupFilesByDirectory(array $files): array
    {
        $grouped = [];

        foreach ($files as $file) {
            $dir = dirname($file['relativePath']);
            if ($dir === '.') {
                $dir = '.';
            }
            if (!isset($grouped[$dir])) {
                $grouped[$dir] = [];
            }
            $grouped[$dir][] = $file;
        }

        // Sort directories
        ksort($grouped);

        // Sort files within each directory
        foreach ($grouped as $dir => $filesInDir) {
            usort($grouped[$dir], function ($a, $b) {
                return strcmp($a['relativePath'], $b['relativePath']);
            });
        }

        return $grouped;
    }

    /**
     * Escape special markdown characters.
     *
     * @param string $text The text to escape
     * @return string The escaped text
     */
    private function escapeForMarkdown(string $text): string
    {
        $toEscape = ['[', ']', '(', ')', '*', '_', '`', '#'];
        $escaped = str_replace($toEscape, ['\\[', '\\]', '\\(', '\\)', '\\*', '\\_', '\\`', '\\#'], $text);
        return $escaped;
    }
}
