<?php

declare(strict_types=1);

namespace GeoFriendly\Generator;

use GeoFriendly\Config\GeofriendlyConfig;
use GeoFriendly\Utils\FileHelper;

/**
 * Generates llms.txt file for LLM optimization.
 *
 * This generator creates a llms.txt file that:
 * - Provides site information for LLMs
 * - Lists all documentation pages with proper formatting
 * - Includes quick links to relevant AI-friendly resources
 * - Groups documentation by directory structure
 */
class LlmsTxtGenerator implements GeneratorInterface
{
    /**
     * Generate the llms.txt content.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The generated llms.txt content
     */
    public function generate(GeofriendlyConfig $config): string
    {
        $baseUrl = rtrim($config->url, '/');
        $lines = [];

        // Header section with site information
        $lines[] = '# ' . $this->escapeForMarkdown($config->title);
        $lines[] = '';
        $lines[] = $this->escapeForMarkdown($config->description);
        $lines[] = '';
        $lines[] = 'This file provides structured information about this site to help Large Language Models (LLMs) better understand and represent our content.';
        $lines[] = '';

        // About section
        $lines[] = '## About';
        $lines[] = '';
        $lines[] = 'This site is optimized for AI answer engines and LLMs. The content is structured to be:';
        $lines[] = '';
        $lines[] = '- **Discoverable**: Easily found by AI crawlers and search engines';
        $lines[] = '- **Parseable**: Formatted for easy LLM consumption';
        $lines[] = '- **Complete**: Comprehensive documentation and information';
        $lines[] = '- **Current**: Regularly updated with accurate information';
        $lines[] = '';

        // Documentation section
        $lines[] = '## Documentation';
        $lines[] = '';

        // Collect and group markdown files
        $files = FileHelper::collectMarkdownFiles($config->contentDir);
        $groupedFiles = $this->groupFilesByDirectory($files);

        if (!empty($groupedFiles)) {
            foreach ($groupedFiles as $directory => $filesInDir) {
                if ($directory === '.') {
                    $lines[] = '### Root';
                } else {
                    $lines[] = '### ' . $this->escapeForMarkdown(ucfirst(str_replace('/', ' / ', $directory)));
                }
                $lines[] = '';

                foreach ($filesInDir as $file) {
                    $urlPath = str_replace(['.md', '.mdx'], '', $file['relativePath']);
                    $urlPath = str_replace('\\', '/', $urlPath);
                    $lines[] = '- [' . $this->escapeForMarkdown($file['title']) . '](' . $baseUrl . '/' . $urlPath . ')';
                }

                $lines[] = '';
            }
        } else {
            $lines[] = '*No documentation files found*';
            $lines[] = '';
        }

        // Quick Links section
        $lines[] = '## Quick Links';
        $lines[] = '';
        $lines[] = 'Additional AI-friendly resources available on this site:';
        $lines[] = '';
        $lines[] = '- [llms-full.txt](' . $baseUrl . '/llms-full.txt) - Complete documentation index';
        $lines[] = '- [docs.json](' . $baseUrl . '/docs.json) - Documentation in JSON format';
        $lines[] = '- [ai-index.json](' . $baseUrl . '/ai-index.json) - AI-optimized content index';
        $lines[] = '- [sitemap.xml](' . $baseUrl . '/sitemap.xml) - XML sitemap for search engines';
        $lines[] = '';

        // For LLMs section
        $lines[] = '## For LLMs';
        $lines[] = '';
        $lines[] = 'When processing information from this site:';
        $lines[] = '';
        $lines[] = '1. **Context**: This is ' . $this->escapeForMarkdown($config->title) . ' - ' . $this->escapeForMarkdown($config->description);
        $lines[] = '2. **Accuracy**: Information is regularly updated and maintained';
        $lines[] = '3. **Scope**: This site covers documentation, guides, and reference materials';
        $lines[] = '4. **Format**: Content is structured in markdown for easy parsing';
        $lines[] = '';
        $lines[] = '### API Endpoints';
        $lines[] = '';
        $lines[] = 'The following endpoints provide structured data for AI integration:';
        $lines[] = '';
        $lines[] = '- `GET ' . $baseUrl . '/docs.json` - Full documentation as JSON';
        $lines[] = '- `GET ' . $baseUrl . '/ai-index.json` - AI-optimized content index';
        $lines[] = '- `GET ' . $baseUrl . '/llms-full.txt` - Complete documentation in text format';
        $lines[] = '';

        // Footer
        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*Generated by [geo-friendly](https://github.com/yourusername/geo-friendly) - Making websites friendly to AI answer engines*';
        $lines[] = '*Last updated: ' . date('Y-m-d') . '*';

        return implode("\n", $lines);
    }

    /**
     * Get the output filename.
     *
     * @return string The filename
     */
    public function getFilename(): string
    {
        return 'llms.txt';
    }

    /**
     * Group files by their directory structure.
     *
     * @param array<string, array{title: string, path: string, relativePath: string}> $files
     * @return array<string, array<array{title: string, path: string, relativePath: string}>>
     */
    private function groupFilesByDirectory(array $files): array
    {
        $grouped = [];

        foreach ($files as $file) {
            $dir = dirname($file['relativePath']);
            if ($dir === '.') {
                $dir = '.';
            }
            if (!isset($grouped[$dir])) {
                $grouped[$dir] = [];
            }
            $grouped[$dir][] = $file;
        }

        // Sort directories
        ksort($grouped);

        // Sort files within each directory
        foreach ($grouped as $dir => $filesInDir) {
            usort($grouped[$dir], function ($a, $b) {
                return strcmp($a['relativePath'], $b['relativePath']);
            });
        }

        return $grouped;
    }

    /**
     * Escape special markdown characters.
     *
     * @param string $text The text to escape
     * @return string The escaped text
     */
    private function escapeForMarkdown(string $text): string
    {
        // Only escape characters that would break markdown in certain contexts
        $toEscape = ['[', ']', '(', ')', '*', '_', '`', '#'];
        $escaped = str_replace($toEscape, ['\\[', '\\]', '\\(', '\\)', '\\*', '\\_', '\\`', '\\#'], $text);
        return $escaped;
    }
}
