<?php

declare(strict_types=1);

namespace GeoFriendly\Generator;

use GeoFriendly\Config\GeofriendlyConfig;
use GeoFriendly\Utils\FileHelper;

/**
 * Generates llms-full.txt file for complete documentation.
 *
 * This generator creates a llms-full.txt file that concatenates all markdown
 * documentation into a single file with:
 * - Header with title
 * - Table of contents
 * - Each document as a separated section
 * - Source path, title, description, and content for each file
 * - Footer with attribution
 */
class LlmsFullTxtGenerator implements GeneratorInterface
{
    /**
     * Generate the llms-full.txt content.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The generated llms-full.txt content
     */
    public function generate(GeofriendlyConfig $config): string
    {
        $lines = [];

        // Header section
        $lines[] = '# ' . $this->escapeForMarkdown($config->title) . ' - Complete Documentation';
        $lines[] = '';
        if (!empty($config->description)) {
            $lines[] = $this->escapeForMarkdown($config->description);
            $lines[] = '';
        }
        $lines[] = '*This file contains the complete documentation content for ' . $this->escapeForMarkdown($config->title) . '*';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        // Collect markdown files
        $files = FileHelper::collectMarkdownFiles($config->contentDir);

        if (!empty($files)) {
            // Table of Contents section
            $lines[] = '## Table of Contents';
            $lines[] = '';

            foreach ($files as $index => $file) {
                $sectionNumber = $index + 1;
                $lines[] = $sectionNumber . '. [' . $this->escapeForMarkdown($file['title']) . '](#section-' . $sectionNumber . ')';
            }

            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';

            // Content sections
            foreach ($files as $index => $file) {
                $sectionNumber = $index + 1;

                // Section header
                $lines[] = '## Section ' . $sectionNumber . ': ' . $this->escapeForMarkdown($file['title']);
                $lines[] = '';

                // Source path
                $lines[] = '**Source:** `' . $this->escapeForMarkdown($file['relativePath']) . '`';
                $lines[] = '';

                // Read file content
                $content = file_get_contents($file['path']);
                if ($content === false) {
                    $content = '';
                }

                // Extract description from frontmatter if available
                $frontmatter = FileHelper::parseFrontmatter($content);
                if (isset($frontmatter['description']) && is_string($frontmatter['description'])) {
                    $lines[] = '**Description:** ' . $this->escapeForMarkdown($frontmatter['description']);
                    $lines[] = '';
                }

                // Strip frontmatter and add content
                $content = $this->stripFrontmatter($content);
                $lines[] = trim($content);
                $lines[] = '';
                $lines[] = '---';
                $lines[] = '';
            }
        } else {
            // No markdown files found - include basic site overview
            $lines[] = '## Site Overview';
            $lines[] = '';
            $lines[] = 'No markdown documentation files were found in the content directory.';
            $lines[] = '';
            $lines[] = '### Site Information';
            $lines[] = '';
            $lines[] = '- **Title:** ' . $this->escapeForMarkdown($config->title);
            $lines[] = '- **URL:** ' . $this->escapeForMarkdown($config->url);
            if (!empty($config->description)) {
                $lines[] = '- **Description:** ' . $this->escapeForMarkdown($config->description);
            }
            $lines[] = '';
            $lines[] = '---';
            $lines[] = '';
        }

        // Footer section
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*Generated by [geo-friendly](https://github.com/yourusername/geo-friendly) - Making websites friendly to AI answer engines*';
        $lines[] = '';
        $lines[] = '## Resources';
        $lines[] = '';
        $baseUrl = rtrim($config->url, '/');
        $lines[] = '- [llms.txt](' . $baseUrl . '/llms.txt) - Site information for LLMs';
        $lines[] = '- [docs.json](' . $baseUrl . '/docs.json) - Documentation in JSON format';
        $lines[] = '- [ai-index.json](' . $baseUrl . '/ai-index.json) - AI-optimized content index';
        $lines[] = '- [sitemap.xml](' . $baseUrl . '/sitemap.xml) - XML sitemap for search engines';
        $lines[] = '';
        $lines[] = '*Last updated: ' . date('Y-m-d H:i:s') . '*';

        return implode("\n", $lines);
    }

    /**
     * Get the output filename.
     *
     * @return string The filename
     */
    public function getFilename(): string
    {
        return 'llms-full.txt';
    }

    /**
     * Strip YAML frontmatter from content.
     *
     * @param string $content The file content
     * @return string The content without frontmatter
     */
    private function stripFrontmatter(string $content): string
    {
        return preg_replace('/^---\s*\n.*?\n---\s*\n/s', '', $content);
    }

    /**
     * Escape special markdown characters.
     *
     * @param string $text The text to escape
     * @return string The escaped text
     */
    private function escapeForMarkdown(string $text): string
    {
        // Only escape characters that would break markdown in certain contexts
        $toEscape = ['[', ']', '(', ')', '*', '_', '`', '#'];
        $escaped = str_replace($toEscape, ['\\[', '\\]', '\\(', '\\)', '\\*', '\\_', '\\`', '\\#'], $text);
        return $escaped;
    }
}
