<?php

declare(strict_types=1);

namespace GeoFriendly\Generator;

use GeoFriendly\Config\GeofriendlyConfig;
use GeoFriendly\Utils\FileHelper;

/**
 * Generates llms.txt file for LLM optimization.
 *
 * This generator creates a llms.txt file that:
 * - Provides site information for LLMs
 * - Lists all documentation pages with proper formatting
 * - Includes quick links to relevant AI-friendly resources
 * - Groups documentation by directory structure
 * - Supports both file-based and array-based content
 */
class LlmsTxtGenerator implements GeneratorInterface
{
    /**
     * Generate the llms.txt content.
     *
     * @param GeofriendlyConfig $config The configuration object
     * @return string The generated llms.txt content
     */
    public function generate(GeofriendlyConfig $config): string
    {
        $baseUrl = rtrim($config->url, '/');
        $lines = [];

        // Header section with site information
        $lines[] = '# ' . $this->escapeForMarkdown($config->title);
        $lines[] = '';
        $lines[] = $this->escapeForMarkdown($config->description);
        $lines[] = '';
        $lines[] = 'This file provides structured information about this site to help Large Language Models (LLMs) better understand and represent our content.';
        $lines[] = '';

        // About section
        $lines[] = '## About';
        $lines[] = '';
        $lines[] = 'This site is optimized for AI answer engines and LLMs. The content is structured to be:';
        $lines[] = '';
        $lines[] = '- **Discoverable**: Easily found by AI crawlers and search engines';
        $lines[] = '- **Parseable**: Formatted for easy LLM consumption';
        $lines[] = '- **Complete**: Comprehensive documentation and information';
        $lines[] = '- **Current**: Regularly updated with accurate information';
        $lines[] = '';

        // Documentation section
        $lines[] = '## Documentation';
        $lines[] = '';

        // Collect content from files or array
        $contentItems = FileHelper::collectContent($config);

        // If using content array, group by category
        if ($config->hasContentArray()) {
            $groupedItems = $this->groupContentByCategory($contentItems);
        } else {
            $groupedItems = $this->groupContentByDirectory($contentItems);
        }

        if (!empty($groupedItems)) {
            foreach ($groupedItems as $group => $items) {
                $lines[] = '### ' . $this->escapeForMarkdown($group);
                $lines[] = '';

                foreach ($items as $item) {
                    $lines[] = '- [' . $this->escapeForMarkdown($item['title']) . '](' . $baseUrl . $item['url'] . ')';
                }

                $lines[] = '';
            }
        } else {
            $lines[] = '*No documentation files found*';
            $lines[] = '';
        }

        // Quick Links section
        $lines[] = '## Quick Links';
        $lines[] = '';
        $lines[] = 'Additional AI-friendly resources available on this site:';
        $lines[] = '';
        $lines[] = '- [llms-full.txt](' . $baseUrl . '/llms-full.txt) - Complete documentation index';
        $lines[] = '- [docs.json](' . $baseUrl . '/docs.json) - Documentation in JSON format';
        $lines[] = '- [ai-index.json](' . $baseUrl . '/ai-index.json) - AI-optimized content index';
        $lines[] = '- [sitemap.xml](' . $baseUrl . '/sitemap.xml) - XML sitemap for search engines';
        $lines[] = '';

        // For LLMs section
        $lines[] = '## For LLMs';
        $lines[] = '';
        $lines[] = 'When processing information from this site:';
        $lines[] = '';
        $lines[] = '1. **Context**: This is ' . $this->escapeForMarkdown($config->title) . ' - ' . $this->escapeForMarkdown($config->description);
        $lines[] = '2. **Accuracy**: Information is regularly updated and maintained';
        $lines[] = '3. **Scope**: This site covers documentation, guides, and reference materials';
        $lines[] = '4. **Format**: Content is structured in markdown for easy parsing';
        $lines[] = '';
        $lines[] = '### API Endpoints';
        $lines[] = '';
        $lines[] = 'The following endpoints provide structured data for AI integration:';
        $lines[] = '';
        $lines[] = '- `GET ' . $baseUrl . '/docs.json` - Full documentation as JSON';
        $lines[] = '- `GET ' . $baseUrl . '/ai-index.json` - AI-optimized content index';
        $lines[] = '- `GET ' . $baseUrl . '/llms-full.txt` - Complete documentation in text format';
        $lines[] = '';

        // Footer
        $lines[] = '---';
        $lines[] = '';
        $lines[] = '*Generated by [geo-friendly](https://github.com/wzj177/geo-friendly) - Making websites friendly to AI answer engines*';
        $lines[] = '*Last updated: ' . date('Y-m-d') . '*';

        return implode("\n", $lines);
    }

    /**
     * Get the output filename.
     *
     * @return string The filename
     */
    public function getFilename(): string
    {
        return 'llms.txt';
    }

    /**
     * Group content by category (for content arrays).
     *
     * @param array<string, array{title: string, content: string, url: string, relativePath: string, description: string|null, category: string|null, tags: array<string>}> $items
     * @return array<string, array<array{title: string, content: string, url: string, relativePath: string, description: string|null, category: string|null, tags: array<string>}>>
     */
    private function groupContentByCategory(array $items): array
    {
        $grouped = [];

        foreach ($items as $item) {
            $category = $item['category'] ?? 'General';
            if (!isset($grouped[$category])) {
                $grouped[$category] = [];
            }
            $grouped[$category][] = $item;
        }

        // Sort categories
        ksort($grouped);

        // Sort items within each category
        foreach ($grouped as $category => $categoryItems) {
            usort($grouped[$category], function ($a, $b) {
                return strcmp($a['title'], $b['title']);
            });
        }

        return $grouped;
    }

    /**
     * Group content by directory (for file-based content).
     *
     * @param array<string, array{title: string, content: string, url: string, relativePath: string, description: string|null, category: string|null, tags: array<string>}> $items
     * @return array<string, array<array{title: string, content: string, url: string, relativePath: string, description: string|null, category: string|null, tags: array<string>}>>
     */
    private function groupContentByDirectory(array $items): array
    {
        $grouped = [];

        foreach ($items as $item) {
            $dir = dirname($item['relativePath']);
            if ($dir === '.') {
                $dir = 'Root';
            }
            if (!isset($grouped[$dir])) {
                $grouped[$dir] = [];
            }
            $grouped[$dir][] = $item;
        }

        // Sort directories
        ksort($grouped);

        // Sort items within each directory
        foreach ($grouped as $dir => $dirItems) {
            usort($grouped[$dir], function ($a, $b) {
                return strcmp($a['relativePath'], $b['relativePath']);
            });
        }

        return $grouped;
    }

    /**
     * Escape special markdown characters.
     *
     * @param string $text The text to escape
     * @return string The escaped text
     */
    private function escapeForMarkdown(string $text): string
    {
        // Only escape characters that would break markdown in certain contexts
        $toEscape = ['[', ']', '(', ')', '*', '_', '`', '#'];
        $escaped = str_replace($toEscape, ['\\[', '\\]', '\\(', '\\)', '\\*', '\\_', '\\`', '\\#'], $text);
        return $escaped;
    }
}
