import { readdirSync, readFileSync, statSync, existsSync } from 'fs';
import { join, relative, extname } from 'path';
import type { ResolvedAeoConfig } from '../types';
import { parseFrontmatter, bumpHeadings } from './utils';

function collectAndConcatenateMarkdown(dir: string, base: string = dir): string[] {
  const sections: string[] = [];
  
  try {
    const entries = readdirSync(dir).sort();
    
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const stat = statSync(fullPath);
      
      if (stat.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules') {
        const subSections = collectAndConcatenateMarkdown(fullPath, base);
        if (subSections.length > 0) {
          sections.push(...subSections);
        }
      } else if (stat.isFile() && (extname(entry) === '.md' || extname(entry) === '.mdx')) {
        const content = readFileSync(fullPath, 'utf-8');
        const { frontmatter, content: mainContent } = parseFrontmatter(content);
        const relativePath = relative(base, fullPath);
        
        const sectionLines: string[] = [
          '---',
          '',
          `# ${frontmatter.title || relativePath}`,
          '',
          `Source: ${relativePath}`,
          '',
        ];
        
        if (frontmatter.description) {
          sectionLines.push(`> ${frontmatter.description}`);
          sectionLines.push('');
        }
        
        const bumpedContent = bumpHeadings(mainContent, 1);
        sectionLines.push(bumpedContent);
        sectionLines.push('');
        
        sections.push(sectionLines.join('\n'));
      }
    }
  } catch (error) {
    console.warn(`Warning: Could not read directory ${dir}:`, error);
  }
  
  return sections;
}

export function generateLlmsFull(config: ResolvedAeoConfig): string {
  return generateLlmsFullTxt(config);
}

export function generateLlmsFullTxt(config: ResolvedAeoConfig): string {
  const lines: string[] = [
    `# ${config.title} - Complete Documentation`,
    '',
    `This file contains all documentation concatenated into a single file for easy consumption by LLMs.`,
    '',
  ];
  
  if (config.description) {
    lines.push(`> ${config.description}`);
    lines.push('');
  }
  
  lines.push('## Table of Contents');
  lines.push('');
  lines.push('This document includes all content from this project.');
  lines.push('Each section is separated by a horizontal rule (---) for easy parsing.');
  lines.push('');

  let hasContent = false;

  // Include discovered pages (from framework plugin)
  if (config.pages && config.pages.length > 0) {
    for (const page of config.pages) {
      const url = `${config.url}${page.pathname === '/' ? '' : page.pathname}`;
      const title = page.title || page.pathname;
      const sectionLines: string[] = [
        '---',
        '',
        `# ${title}`,
        '',
        `URL: ${url}`,
        '',
      ];
      if (page.description) {
        sectionLines.push(`> ${page.description}`);
        sectionLines.push('');
      }
      if (page.content) {
        sectionLines.push(page.content);
        sectionLines.push('');
      }
      lines.push(sectionLines.join('\n'));
      hasContent = true;
    }
  }

  // Include markdown content files
  const sections = existsSync(config.contentDir) ? collectAndConcatenateMarkdown(config.contentDir) : [];

  if (sections.length > 0) {
    lines.push(...sections);
    hasContent = true;
  }

  if (!hasContent) {
    // Always include site overview so LLMs have basic context
    lines.push('---');
    lines.push('');
    lines.push(`# ${config.title}`);
    lines.push('');
    lines.push(`URL: ${config.url}`);
    lines.push('');
    if (config.description) {
      lines.push(config.description);
      lines.push('');
    }
  }
  
  lines.push('---');
  lines.push('');
  lines.push('## About This Document');
  lines.push('');
  lines.push('This concatenated documentation file is generated automatically by aeo.js');
  lines.push('to make it easier for AI systems to understand the complete context of this project.');
  lines.push('');
  lines.push(`For a structured index, see: ${config.url}/llms.txt`);
  lines.push(`For individual files, see: ${config.url}/docs.json`);
  lines.push('');
  lines.push('Generated by aeo.js - https://aeojs.org');
  
  return lines.join('\n');
}