import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateLlmsTxt } from './llms-txt';
import type { ResolvedAeoConfig } from '../types';

vi.mock('fs', () => ({
  readdirSync: vi.fn().mockReturnValue([]),
  statSync: vi.fn(),
  readFileSync: vi.fn().mockReturnValue('# Test\n\nContent'),
  existsSync: vi.fn().mockReturnValue(false),
}));

const baseConfig: ResolvedAeoConfig = {
  url: 'https://example.com',
  title: 'Test Project',
  description: 'A test project description',
  contentDir: '/project/content',
  outDir: 'public',
  pages: [],
  generators: {
    robotsTxt: true,
    llmsTxt: true,
    llmsFullTxt: true,
    rawMarkdown: true,
    manifest: true,
    sitemap: true,
    aiIndex: true,
    schema: true,
  },
  robots: { allow: ['/'], disallow: [], crawlDelay: 0, sitemap: '' },
  widget: {
    enabled: true,
    position: 'bottom-right',
    theme: { background: '#000', text: '#fff', accent: '#eee', badge: '#4ADE80' },
    humanLabel: 'Human',
    aiLabel: 'AI',
    showBadge: true,
    size: 'default' as const,
  },
  schema: {
    enabled: true,
    organization: { name: 'Test', url: 'https://example.com', logo: '', sameAs: [] },
    defaultType: 'WebPage',
  },
  og: {
    enabled: false,
    image: '',
    twitterHandle: '',
    type: 'website',
  },
};

describe('generateLlmsTxt', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should generate llms.txt with project title and description', () => {
    const result = generateLlmsTxt(baseConfig);

    expect(result).toContain('# Test Project');
    expect(result).toContain('> A test project description');
  });

  it('should include about section', () => {
    const result = generateLlmsTxt(baseConfig);

    expect(result).toContain('## About');
    expect(result).toContain('This file provides a structured overview');
    expect(result).toContain('optimized for consumption by Large Language Models');
  });

  it('should include quick links', () => {
    const result = generateLlmsTxt(baseConfig);

    expect(result).toContain('## Quick Links');
    expect(result).toContain('Full Documentation: https://example.com/llms-full.txt');
    expect(result).toContain('Documentation Manifest: https://example.com/docs.json');
    expect(result).toContain('AI-Optimized Index: https://example.com/ai-index.json');
    expect(result).toContain('Sitemap: https://example.com/sitemap.xml');
  });

  it('should include LLM instructions', () => {
    const result = generateLlmsTxt(baseConfig);

    expect(result).toContain('## For LLMs');
    expect(result).toContain('https://example.com/llms-full.txt');
    expect(result).toContain('https://example.com/docs.json');
    expect(result).toContain('https://example.com/ai-index.json');
  });

  it('should include footer', () => {
    const result = generateLlmsTxt(baseConfig);

    expect(result).toContain('Generated by aeo.js');
    expect(result).toContain('Learn more at https://aeojs.org');
  });

  it('should handle missing description', () => {
    const config: ResolvedAeoConfig = { ...baseConfig, description: '' };
    const result = generateLlmsTxt(config);

    expect(result).toContain('# Test Project');
    // Should not have empty blockquote
    expect(result).not.toContain('> \n');
  });

  it('should include pages section when pages exist', () => {
    const config: ResolvedAeoConfig = {
      ...baseConfig,
      pages: [
        { pathname: '/', title: 'Home' },
        { pathname: '/about', title: 'About Us' },
      ],
    };
    const result = generateLlmsTxt(config);

    expect(result).toContain('## Pages');
    expect(result).toContain('Home');
    expect(result).toContain('About Us');
  });
});
