import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateLlmsFullTxt } from './llms-full';
import type { ResolvedAeoConfig } from '../types';

vi.mock('fs', () => ({
  readdirSync: vi.fn().mockReturnValue([]),
  statSync: vi.fn(),
  readFileSync: vi.fn().mockReturnValue('# Test\n\nContent'),
  existsSync: vi.fn().mockReturnValue(false),
}));

const baseConfig: ResolvedAeoConfig = {
  url: 'https://example.com',
  title: 'Test Project',
  description: 'A test project description',
  contentDir: '/project/content',
  outDir: 'public',
  pages: [],
  generators: {
    robotsTxt: true,
    llmsTxt: true,
    llmsFullTxt: true,
    rawMarkdown: true,
    manifest: true,
    sitemap: true,
    aiIndex: true,
    schema: true,
  },
  robots: { allow: ['/'], disallow: [], crawlDelay: 0, sitemap: '' },
  widget: {
    enabled: true,
    position: 'bottom-right',
    theme: { background: '#000', text: '#fff', accent: '#eee', badge: '#4ADE80' },
    humanLabel: 'Human',
    aiLabel: 'AI',
    showBadge: true,
    size: 'default' as const,
  },
  schema: {
    enabled: true,
    organization: { name: 'Test', url: 'https://example.com', logo: '', sameAs: [] },
    defaultType: 'WebPage',
  },
  og: {
    enabled: false,
    image: '',
    twitterHandle: '',
    type: 'website',
  },
};

describe('generateLlmsFullTxt', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should generate complete documentation header', () => {
    const result = generateLlmsFullTxt(baseConfig);

    expect(result).toContain('# Test Project - Complete Documentation');
    expect(result).toContain('> A test project description');
  });

  it('should include table of contents section', () => {
    const result = generateLlmsFullTxt(baseConfig);

    expect(result).toContain('## Table of Contents');
    expect(result).toContain('Each section is separated by a horizontal rule');
  });

  it('should include page content when pages have content', () => {
    const config: ResolvedAeoConfig = {
      ...baseConfig,
      pages: [
        { pathname: '/', title: 'Home', content: 'Welcome to our site' },
        { pathname: '/about', title: 'About', description: 'About us', content: 'We are great' },
      ],
    };

    const result = generateLlmsFullTxt(config);

    expect(result).toContain('# Home');
    expect(result).toContain('Welcome to our site');
    expect(result).toContain('# About');
    expect(result).toContain('We are great');
    expect(result).toContain('URL: https://example.com');
    expect(result).toContain('URL: https://example.com/about');
  });

  it('should include separator between pages', () => {
    const config: ResolvedAeoConfig = {
      ...baseConfig,
      pages: [
        { pathname: '/', title: 'Home', content: 'Home content' },
        { pathname: '/about', title: 'About', content: 'About content' },
      ],
    };

    const result = generateLlmsFullTxt(config);
    const separatorCount = (result.match(/^---$/gm) || []).length;

    expect(separatorCount).toBeGreaterThan(0);
  });

  it('should include footer', () => {
    const result = generateLlmsFullTxt(baseConfig);

    expect(result).toContain('## About This Document');
    expect(result).toContain('Generated by aeo.js');
    expect(result).toContain('https://aeojs.org');
  });

  it('should include fallback content when no pages exist', () => {
    const result = generateLlmsFullTxt(baseConfig);

    // Should still have the site title in the content
    expect(result).toContain('# Test Project');
    expect(result).toContain('URL: https://example.com');
  });
});
