import { readdirSync, readFileSync, statSync, existsSync } from 'fs';
import { join, relative, extname } from 'path';
import type { ResolvedAeoConfig, MarkdownFile } from '../types';
import { parseFrontmatter, extractTitle } from './utils';

function collectMarkdownFiles(dir: string, base: string = dir): MarkdownFile[] {
  const files: MarkdownFile[] = [];
  
  try {
    const entries = readdirSync(dir);
    
    for (const entry of entries) {
      const fullPath = join(dir, entry);
      const stat = statSync(fullPath);
      
      const SKIP_DIRS = new Set(['node_modules', 'public', 'dist', '.next', '.nuxt', '.output', '.open-next', 'coverage', '__tests__', '__mocks__']);
      if (stat.isDirectory() && !entry.startsWith('.') && !SKIP_DIRS.has(entry)) {
        files.push(...collectMarkdownFiles(fullPath, base));
      } else if (stat.isFile() && (extname(entry) === '.md' || extname(entry) === '.mdx')) {
        const content = readFileSync(fullPath, 'utf-8');
        const { frontmatter, content: mainContent } = parseFrontmatter(content);
        const relativePath = relative(base, fullPath);
        
        files.push({
          path: relativePath,
          content: mainContent,
          title: frontmatter.title || extractTitle(mainContent),
          description: frontmatter.description,
          frontmatter,
        });
      }
    }
  } catch (error) {
    console.warn(`Warning: Could not read directory ${dir}:`, error);
  }
  
  return files;
}

export function generateLlmsTxt(config: ResolvedAeoConfig): string {
  const lines: string[] = [
    `# ${config.title}`,
    '',
  ];
  
  if (config.description) {
    lines.push(`> ${config.description}`);
    lines.push('');
  }
  
  lines.push('## About');
  lines.push('');
  lines.push('This file provides a structured overview of the documentation and content available on this site,');
  lines.push('optimized for consumption by Large Language Models (LLMs) and AI assistants.');
  lines.push('');
  
  // List discovered pages (from framework plugin)
  if (config.pages && config.pages.length > 0) {
    lines.push('## Pages');
    lines.push('');

    for (const page of config.pages) {
      const url = `${config.url}${page.pathname === '/' ? '' : page.pathname}`;
      const title = page.title || page.pathname;
      lines.push(`- [${title}](${url})`);
      if (page.description) {
        lines.push(`  ${page.description}`);
      }
    }
    lines.push('');
  }

  // List markdown content files
  const markdownFiles = existsSync(config.contentDir) ? collectMarkdownFiles(config.contentDir) : [];

  if (markdownFiles.length > 0) {
    lines.push('## Documentation');
    lines.push('');

    const grouped: Record<string, MarkdownFile[]> = {};

    for (const file of markdownFiles) {
      const dir = file.path.split('/')[0] || 'root';
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(file);
    }

    for (const [dir, files] of Object.entries(grouped)) {
      lines.push(`### ${dir === 'root' ? 'Main Documentation' : dir}`);
      lines.push('');

      for (const file of files) {
        const url = `${config.url}/${file.path.replace(/\.mdx?$/, '')}`;
        lines.push(`- [${file.title}](${url})`);
        if (file.description) {
          lines.push(`  ${file.description}`);
        }
      }
      lines.push('');
    }
  }
  
  lines.push('## Quick Links');
  lines.push('');
  lines.push(`- Full Documentation: ${config.url}/llms-full.txt`);
  lines.push(`- Documentation Manifest: ${config.url}/docs.json`);
  lines.push(`- AI-Optimized Index: ${config.url}/ai-index.json`);
  lines.push(`- Sitemap: ${config.url}/sitemap.xml`);
  lines.push('');
  
  lines.push('## For LLMs');
  lines.push('');
  lines.push('To get the complete documentation in a single file, request:');
  lines.push(`${config.url}/llms-full.txt`);
  lines.push('');
  lines.push('For structured access to individual pages with metadata:');
  lines.push(`${config.url}/docs.json`);
  lines.push('');
  lines.push('For RAG (Retrieval Augmented Generation) systems:');
  lines.push(`${config.url}/ai-index.json`);
  lines.push('');
  
  lines.push('---');
  lines.push('Generated by aeo.js - Answer Engine Optimization for the modern web');
  lines.push('Learn more at https://aeojs.org');
  
  return lines.join('\n');
}